git_url: git@github.com:zib0/dotfiles.git

dotfiles:
  - bashrc
  - bash_history
  - condarc
  - Rprofile
  - gitconfig
  - profile

dotfolders:
  - config/alacritty
  - config/fish
  - config/iterm2
  - config/kitty
  - config/rstudio
  - hammerspoon

brew:
  - git
  - vim
  - tmux

brew-cask:
  - google-chrome
  - iterm2
  - slack

exclude:
  - "*.swp"
  - id_rsa
  - ./config/nvim/plugged