# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base

    - name: Test Mypy
      run: |
        $CONDA/bin/conda/tox -e py310-mypy
    - name: Test with pytest
      run: |
        $CONDA/bin/conda/tox -e py310-pytest
    - name: Build 
      run: |
        $CONDA/bin/conda/tox -e build
    - name: Build Doc
      run: |
        $CONDA/bin/conda/tox -e doc
    - name: Doc Test
      run: |
        $CONDA/bin/conda/tox -e doctest
    - name: Link Test
      run: |
        $CONDA/bin/conda/tox -e linkcheck
    - name: Clean
      run: |
        $CONDA/bin/conda/tox -e clean
