# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: py310
        environment-file: environment.yml
        python-version: 3.10

    - name: Test Mypy
      run: |
        tox -e py310-mypy
    - name: Test with pytest
      run: |
        tox -e py310-pytest
    - name: Build 
      run: |
        tox -e build
    - name: Build Doc
      run: |
        tox -e doc
    - name: Doc Test
      run: |
        tox -e doctest
    - name: Link Test
      run: |
        tox -e linkcheck
    - name: Clean
      run: |
        tox -e clean
